GDBackend:
  default_quality: 100

Page:
  extensions:
    - PageExtension

ContentController:
  extensions:
    - PageControllerExtension

SiteConfig:
  extensions:
    - BoilerplateSiteConfigExtension

Image:
  extensions:
    - ImageExtension