GDBackend:
  default_quality: 100

Security:
  extensions:
    - SecurityExtension

SiteConfig:
  extensions:
    - BoilerplateConfig

Page:
  extensions:
    - PageExtension

GalleryPage:
  extensions:
    - ColumnsPageExtension

GalleryPage_Controller:
  extensions:
    - ColumnsPageControllerExtension

ContentController:
  extensions:
    - PageControllerExtension