---
Name: boilerplate
After: 'framework/*','cms/*'
---

GDBackend:
  default_quality: 100

Page:
  extensions:
    - BoilerplatePageExtension

SiteConfig:
  extensions:
    - BoilerplateSiteConfigExtension

Image:
  extensions:
    - BoilerplateImageExtension

Group:
  extensions:
    - BoilerplateGroupExtension
