GDBackend:
  default_quality: 100

# SiteConfig
SiteConfig:
  extensions:
    - BoilerplateConfig

# Page
Page:
  extensions:
    - PageExtension

ContentController:
  extensions:
    - PageControllerExtension

# Blog
BlogHolder:
  extensions:
    - ColumnsPageExtension

BlogHolder_Controller:
  extensions:
    - ColumnsPageControllerExtension

# Portfolio
PortfolioHolder:
  extensions:
    - ColumnsPageExtension

PortfolioHolder_Controller:
  extensions:
    - ColumnsPageControllerExtension